
site_name: OneFlow
site_url: https://www.oneflow.org/
site_description: >-
  OneFlow 是一款分布式高效的机器学习框架
# Repository
repo_name: OneFlow
repo_url: https://github.com/OneFlow-Inc/oneflow
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2017 - 2020 OneFlow

#website/xxx.html style
use_directory_urls: false

# Configuration
theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  features:
    - tabs
    #- instant
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo
  favicon: assets/favicon.png

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
    - 首页: index.md

    - 快速上手:
      - 3分钟快速上手: quick_start/quickstart_in_3_min.md
      - 识别MNIST手写体数字: quick_start/lenet_mnist.md

    - 基础专题:
      - tensor与blob: basics_topics/tensor_blob.md
      - get_varaible方法: basics_topics/get_variable.md
      - 任务函数及训练环境配置: basics_topics/job_function_config.md
      - 任务函数的定义与调用: basics_topics/job_function_define_call.md
      - 获取任务函数的结果: basics_topics/async_get.md
      - OFRecord数据集的制作与导入: basics_topics/ofrecord.md
      - 模型的加载与保存: basics_topics/model_load_save.md
      - 分布式训练: basics_topics/distributed_train.md
      - Consistent与Mirrored策略: basics_topics/consistent_mirrored.md
    
    - 高级应用实例:
      - 图像处理:
        - AlexNet: adv_examples/alexnet.md
        - MaskRCNN: adv_examples/mask_rcnn.md
      - 文本处理-BERT: adv_examples/bert.md
      - 推荐系统-Wide&Deep: adv_examples/wide_deep.md
      - 深度伪造-生成对抗网络: adv_examples/dcgan.md

    - 部署与运维:
      - 编译: 
        - 编译源码: build_ship/build_source.md
        - 使用docker编译: build_ship/build_in_docker.md
      - 安装与测试: build_ship/install.md
      - 常见问题: build_ship/troubleshooting.md

    - 二次开发专题:
      - oneflow架构: extended_dev/framework.md
      - User Op: extended_dev/user_op.md
      - 算子描述符: extended_dev/op_desc.md
      - 自动梯度求导: extended_dev/auto_grad.md
      - 图优化: extended_dev/graph_optimize.md
      - 自动并行: extended_dev/auto_parallel.md
      - 代价模型: extended_dev/loss_model.md
      - 自动放置: extended_dev/auto_placement.md
      - 数据路由: extended_dev/data_router.md
      - 内存规划: extended_dev/mem_model.md
      - NDArray: extended_dev/ndarray.md

    - 为OneFlow做贡献:
      - OneFlow开源计划: contribute/intro.md

      - 开发者指南: contribute/developer-guide.md

      - 贡献文档: contribute/doc.md

      - 贡献测试案例: contribute/tests.md

      - 编写WiKi: contribute/wiki.md

      - review PR: contribute/review_pr.md

      - 社区: contribute/community.md